const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let audio;
function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function water(){try{initAudio();let t=audio.currentTime;for(let i=0;i<5;i++){let o=audio.createOscillator(),g=audio.createGain();o.type=i%2?'sine':'triangle';o.frequency.setValueAtTime(260+i*95,t);o.frequency.exponentialRampToValueAtTime(90+i*22,t+.55);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.025,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+.62);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.65)}}catch(e){}}
function say(x){water();if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(x);u.lang='uz-UZ';u.rate=.9;speechSynthesis.speak(u)}}
function animateIn(){setTimeout(()=>$('#loader')?.remove(),450);$$('.reveal,.fall').forEach((e,i)=>setTimeout(()=>e.classList.add('show'),80+i*65));}
addEventListener('load',animateIn);const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.1});$$('.reveal,.fall').forEach(e=>io.observe(e));
addEventListener('pointermove',e=>{let c=$('#cursor'),g=$('.glow');if(c){c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'}if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
$$('.tilt').forEach(el=>{el.addEventListener('pointermove',e=>{let r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${-y*7}deg) translateY(-5px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
$$('[data-sound]').forEach(b=>b.addEventListener('mouseenter',water));$('#sound')?.addEventListener('click',()=>{water();$('#sound').textContent='🔊'});$('#apply')?.addEventListener('click',()=>say('Ariza'));
$$('a[data-page]').forEach(a=>a.addEventListener('click',e=>{let target=new URL(a.href,location.href);if(target.pathname===location.pathname)return;e.preventDefault();water();$('#wave')?.classList.add('go');setTimeout(()=>location.href=a.href,760)}));
function toast(t){let x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}$('#appform')?.addEventListener('submit',e=>{e.preventDefault();say('Ariza qabul qilindi');toast('Arizangiz qabul qilindi ✨');e.target.reset()});
