const courses=[{name:'Arab tili',teacher:'Malika Ahmedova',type:'Online + Offline',lessons:24,icon:'🕌'},{name:'Ingliz tili',teacher:'Sardor Akramov',type:'Online + Offline',lessons:30,icon:'🌍'},{name:'Ona tili',teacher:'Dilnoza Ismoilova',type:'Offline',lessons:20,icon:'📖'}];
function speak(t){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='uz-UZ';u.rate=.9;speechSynthesis.speak(u)}catch(e){}}
function water(){try{let A=new AudioContext(),o=A.createOscillator(),g=A.createGain();o.frequency.setValueAtTime(560,A.currentTime);o.frequency.exponentialRampToValueAtTime(220,A.currentTime+.16);g.gain.setValueAtTime(.04,A.currentTime);g.gain.exponentialRampToValueAtTime(.001,A.currentTime+.18);o.connect(g).connect(A.destination);o.start();o.stop(A.currentTime+.18)}catch(e){}}
document.addEventListener('click',e=>{let a=e.target.closest('a');if(a){water();let t=a.textContent.trim();if(t==='Bosh sahifa'||a.classList.contains('brand'))t='Bosh menyu';if(t)speak(t)}});
function render(id,online=false){let b=document.getElementById(id);if(!b)return;b.innerHTML=courses.map(c=>`<article class="card"><i>${c.icon}</i><h3>${c.name}</h3><p>Ustoz: ${c.teacher}<br>${c.lessons} ta dars • ${c.type}</p><a href="${online?'#':'apply.html'}" onclick="${online?"speak('Online ta’lim');return false":""}">${online?'Kursga kirish →':'Ariza berish →'}</a></article>`).join('')}
render('courses');render('onlineCourses',true);
let form=document.getElementById('applyForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();let d=Object.fromEntries(new FormData(form));d.date=new Date().toLocaleString('uz-UZ');let a=JSON.parse(localStorage.getItem('sofi_applications')||'[]');a.push(d);localStorage.setItem('sofi_applications',JSON.stringify(a));document.getElementById('applyResult').innerHTML='<div class="card">✅ Arizangiz qabul qilindi. Tez orada siz bilan bog‘lanamiz.</div>';speak('Arizangiz qabul qilindi');form.reset()});
let lb=document.getElementById('loginBtn');if(lb)lb.onclick=()=>{let l=document.getElementById('login').value.trim(),p=document.getElementById('password').value;if(l==='Davron'&&p==='Davron2004'){sessionStorage.setItem('sofi_admin','1');showAdmin()}else{document.getElementById('loginMsg').textContent='Login yoki parol noto‘g‘ri.';speak('Login yoki parol noto‘g‘ri')}};
function showAdmin(){let x=document.getElementById('loginBox'),d=document.getElementById('dashboard');if(!x||!d)return;x.hidden=true;d.hidden=false;let a=JSON.parse(localStorage.getItem('sofi_applications')||'[]');document.getElementById('appCount').textContent=a.length;document.getElementById('applications').innerHTML=a.length?a.slice().reverse().map(v=>`<div class="application"><b>${v.name}</b> — ${v.course} (${v.type})<br>📞 ${v.phone} • ${v.age} yosh<br><small>${v.date}${v.note?' • '+v.note:''}</small></div>`).join(''):'Hozircha ariza yo‘q.'}if(sessionStorage.getItem('sofi_admin')==='1')showAdmin();let lo=document.getElementById('logout');if(lo)lo.onclick=()=>{sessionStorage.removeItem('sofi_admin');location.reload()};
